Feature/blocksync
DE-labtory/it-chain pull request #234
Opened 2018-06-19 12:06 UTC by junk-sound

Readme.md 입니다.
많은 피드백 부탁드려요~

2018-06-20 02:22 UTC, junbeomlee commented
아주 좋은 내용인것 같습니다.
이부분은 꼭 모든 분들이 다 보고 코멘트 해주시면 좋을 것 같습니다! 저도 보고 달겠습니다!!
@byron1st @owljoa @frontalnh @hea9549 @KimJunHui

2018-06-20 02:45 UTC, owljoa commented
정리를 무지 잘하셨네요 :+1: 

궁금한 점이 두가지 있습니다.

1. "신뢰할 수 있는 하나의 노드" 확정의 좀 더 자세한 방법이 궁금합니다.

2. 1번 질문에서 해결될수도 있을것 같지만.. 신뢰할 수 있는 하나의 노드에서 필요한 블록정보를 불러온다면 이후에 전체 혹은 다른(?) 노드들과도 블록체인 상태를 비교나 체크 하는 과정이 있나요?

2018-06-20 02:56 UTC, zeroFruit commented
@owljoa 

1. 우선 blockchain 서비스 내에서 "신뢰할 수 있는 노드"들의 후보를 가지고 있습니다. 그리고 동기화를 시작할 때 후보들끼리 chain의 height와 lastSeal을 가지고 비교하게 됩니다. 그리고 1/3 넘게 같은 height와 lastSeal을 가지고 있는 노드를 "신뢰할 수 있는 노드"로 선정하게 됩니다.

2. 아니요. 처음에 "신뢰할 수 있는 노드"들의 후보를 가지고 있는다 했는데 이를 저희는 전체 네트워크의 표본이라고 생각했습니다.

2018-06-20 02:58 UTC, zeroFruit commented
디테일이 조금 부족한 것 같아서 빠른 시일 내에 IMPLEMENTATION_DETAIL 초안도 작성해보도록 하겠습니다!

2018-06-20 05:05 UTC, frontalnh commented
@junk-sound @zeroFruit 알기쉽게 잘 설명해 주셔서 좋네요! ㅎㅎ
이쪽 컴포넌트에 대해 생소한 만큼 공부도 할겸 작성해 주신 내용 토대로 프로세스 블록단위로 그림그려서 commit 해도 될까요?

2018-06-20 05:57 UTC, ttkmw commented
@frontalnh 
@zeroFruit 가 진행중인 걸로 알고 있습니다! ㅜㅜ

2018-06-20 06:07 UTC, frontalnh commented
@junk-sound 아 ㅋㅋ 넵 좋네요

2018-06-21 12:51 UTC, zeroFruit commented
우선 @junk-sound 님과 논의한 blockchain sync implmentation-details 초안 작성해보았습니다.

2018-06-22 04:09 UTC, byron1st commented
"신뢰할 수 있는 노드" 에서 "노드" 라는 것은 다른 it-chain 노드들을 의미하는 것이지요? 그렇다면, 이 노드들의 전체 메타 정보는 아마 p2p 컴포넌트에서 가지고 있을 것 같고, blockchain 컴포넌트는 각 노드가 갖고 있는 블록체인의 height와 lastSeal 정보를 이벤트 소싱 커넥터를 통해 갖고 있는 것이 되는지요?

2018-06-22 11:01 UTC, junk-sound commented
@byron1st 네 맞습니다!

2018-06-24 05:49 UTC, frontalnh requested changes

2018-06-24 05:49 UTC, frontalnh commented on blockchain/PROJECT-IMPLEMENTATION-DETAILS-KR.md
> +먼저 확인(Check)은 (1) '신뢰할 수 있는 노드'(Reliable Node) 선정과 (2) '상태 점검'을 거친다. Reliable Node를 선정하기 위해서 blockchain 컴포넌트는 ['Reliable Node 후보 저장'](#reliable-node-후보-저장) 과정을 통해서 Reliable Node 후보들을 가지고 있다. 선정 방법은 후
어제 논의 내용에서 reliable node를 별도로 선출하지 않고 check를 전체 peer 목록에서 임의로 몇명을 지정하여 height과 seal 을 받아와서 비교하는 것으로 이야기 되지 않았었나요? ㅎㅎ

2018-06-24 05:49 UTC, frontalnh commented on p2p/api/leader_api_test.go
> +//	publisher := adapter.Publisher(func(exchange string, topic string, data interface{}) error {
현재 p2p component의 모든 test가 작성되고 develop에 머지되어 있어서 conflict가 난 것 같습니다.
기존에 주석처리되어있었기 때문에 develp branch를 한번 pull 받으시고 request 해주시면 p2p 컴포넌트 관련 conflict가 없어질 것 같습니다^^

2018-06-24 06:32 UTC, zeroFruit commented on blockchain/PROJECT-IMPLEMENTATION-DETAILS-KR.md
> +먼저 확인(Check)은 (1) '신뢰할 수 있는 노드'(Reliable Node) 선정과 (2) '상태 점검'을 거친다. Reliable Node를 선정하기 위해서 blockchain 컴포넌트는 ['Reliable Node 후보 저장'](#reliable-node-후보-저장) 과정을 통해서 Reliable Node 후보들을 가지고 있다. 선정 방법은 후
지금 수정중입니다!

2018-06-24 06:32 UTC, zeroFruit commented on p2p/api/leader_api_test.go
> +//	publisher := adapter.Publisher(func(exchange string, topic string, data interface{}) error {
넵

2018-06-24 06:42 UTC, zeroFruit commented on blockchain/PROJECT-IMPLEMENTATION-DETAILS-KR.md
> +먼저 확인(Check)은 (1) '신뢰할 수 있는 노드'(Reliable Node) 선정과 (2) '상태 점검'을 거친다. Reliable Node를 선정하기 위해서 blockchain 컴포넌트는 ['Reliable Node 후보 저장'](#reliable-node-후보-저장) 과정을 통해서 Reliable Node 후보들을 가지고 있다. 선정 방법은 후
@frontalnh 
그런데 어제 얘기했을때 어짜피 Construct 단계에서 한 노드를 대상으로 블럭들을 받아와야하기 때문에 p2p에서 피어 정보들을 받아온다음, 그 중에 blockchain height가 가장 긴 노드를 Reliable Node라고 칭하고, 그 노드에서 블록들을 받아온다고 얘기했었던거 같습니다

2018-06-24 06:43 UTC, zeroFruit commented on blockchain/PROJECT-IMPLEMENTATION-DETAILS-KR.md
> +먼저 확인(Check)은 (1) '신뢰할 수 있는 노드'(Reliable Node) 선정과 (2) '상태 점검'을 거친다. Reliable Node를 선정하기 위해서 blockchain 컴포넌트는 ['Reliable Node 후보 저장'](#reliable-node-후보-저장) 과정을 통해서 Reliable Node 후보들을 가지고 있다. 선정 방법은 후
그래서 선출이라는 내용은 그대로 들어갈것 같고 1/3 관련 내용이 빠지고, 후보 저장과 관련된 부분이 빠질 것 같습니다.

2018-06-24 06:52 UTC, frontalnh commented on blockchain/PROJECT-IMPLEMENTATION-DETAILS-KR.md
> +먼저 확인(Check)은 (1) '신뢰할 수 있는 노드'(Reliable Node) 선정과 (2) '상태 점검'을 거친다. Reliable Node를 선정하기 위해서 blockchain 컴포넌트는 ['Reliable Node 후보 저장'](#reliable-node-후보-저장) 과정을 통해서 Reliable Node 후보들을 가지고 있다. 선정 방법은 후
아 그것은 p2p에서 height 과 seal을 가지고 있어야하는데 이에대한 동기화 이슈가 있고 완벽한 동기화가 이루어지지 못한다면 height값이 가장 긴 노드에게 요청하는것이 무의미해 질 것 같습니다!

2018-06-24 06:58 UTC, frontalnh commented on blockchain/PROJECT-IMPLEMENTATION-DETAILS-KR.md
> +먼저 확인(Check)은 (1) '신뢰할 수 있는 노드'(Reliable Node) 선정과 (2) '상태 점검'을 거친다. Reliable Node를 선정하기 위해서 blockchain 컴포넌트는 ['Reliable Node 후보 저장'](#reliable-node-후보-저장) 과정을 통해서 Reliable Node 후보들을 가지고 있다. 선정 방법은 후
저는 싱크시점에 네트워크 내에서 완벽하게 신뢰가능한 노드하고만 이루어져야 한다고생각했었어서 p2p에서 height값을 들고있는것이 맞다고 생각했었는데 it chain에 private 이라 여러 노드와 반복적으로 sync가 이루어져도 문제가 없을것 같다고 준범리가 말했었던 기억이 있습니다

2018-06-24 06:59 UTC, zeroFruit commented on blockchain/PROJECT-IMPLEMENTATION-DETAILS-KR.md
> +먼저 확인(Check)은 (1) '신뢰할 수 있는 노드'(Reliable Node) 선정과 (2) '상태 점검'을 거친다. Reliable Node를 선정하기 위해서 blockchain 컴포넌트는 ['Reliable Node 후보 저장'](#reliable-node-후보-저장) 과정을 통해서 Reliable Node 후보들을 가지고 있다. 선정 방법은 후
음..  그러면 height값이 가장 긴 노드에게 요청하는게 의미가 없겠네요. 정확히 말하면 아무나한테 요청을해도 될거같네요. 그러면 사실 p2p에서 임의의 몇명 정보가 아니라 1명의 정보만 보내줘도 될 것 같습니다.

2018-06-24 07:00 UTC, zeroFruit commented on blockchain/PROJECT-IMPLEMENTATION-DETAILS-KR.md
> +먼저 확인(Check)은 (1) '신뢰할 수 있는 노드'(Reliable Node) 선정과 (2) '상태 점검'을 거친다. Reliable Node를 선정하기 위해서 blockchain 컴포넌트는 ['Reliable Node 후보 저장'](#reliable-node-후보-저장) 과정을 통해서 Reliable Node 후보들을 가지고 있다. 선정 방법은 후
왜냐하면 그 보내준 1명이 비록 height가 짧은 친구라도 나중에 합의된 블록을 받았을 때 만약 그 블록이 height가 더 큰 블록이라면 그 때 다시 싱크를 시작해도되니까요

2018-06-24 07:01 UTC, zeroFruit commented on blockchain/PROJECT-IMPLEMENTATION-DETAILS-KR.md
> +먼저 확인(Check)은 (1) '신뢰할 수 있는 노드'(Reliable Node) 선정과 (2) '상태 점검'을 거친다. Reliable Node를 선정하기 위해서 blockchain 컴포넌트는 ['Reliable Node 후보 저장'](#reliable-node-후보-저장) 과정을 통해서 Reliable Node 후보들을 가지고 있다. 선정 방법은 후
이렇게되면 blockchain쪽에서 노드 몇명의 정보를 받아와서 비교하는게 의미가 없어보이네요! 그냥 아무나한테 하면되니까

2018-06-24 07:07 UTC, frontalnh commented on blockchain/PROJECT-IMPLEMENTATION-DETAILS-KR.md
> +먼저 확인(Check)은 (1) '신뢰할 수 있는 노드'(Reliable Node) 선정과 (2) '상태 점검'을 거친다. Reliable Node를 선정하기 위해서 blockchain 컴포넌트는 ['Reliable Node 후보 저장'](#reliable-node-후보-저장) 과정을 통해서 Reliable Node 후보들을 가지고 있다. 선정 방법은 후
음 생각해보니 피어테이블에 길이를 들고있다면 여러모로 편리하긴하겠네요
 일단 두가지 고민이 있습니다

1. 만약 단일노드에 요청방식이라면 height이 가장 긴 노드를 만나기까지 계속해서 반복해서 요청하여 많은 자원소모가 잇을것 같습니다 만약 다수에게 보낸다면 피어노드들/요청노드수 번 정도안에 싱크가 완성될 것 같습니다

2. 피어목록에 height을 가지면 다 햐결되긴할거 같은데 동기화이슈를 고민해보아야 겠네요 혹시 좋은 해안이 있을까요?

제가 지금 이동중이라 일단 집에들어가서 고민을 좀 더 해보아야겠습니다 ㅜㅜ

2018-06-24 07:19 UTC, zeroFruit commented on blockchain/PROJECT-IMPLEMENTATION-DETAILS-KR.md
> +먼저 확인(Check)은 (1) '신뢰할 수 있는 노드'(Reliable Node) 선정과 (2) '상태 점검'을 거친다. Reliable Node를 선정하기 위해서 blockchain 컴포넌트는 ['Reliable Node 후보 저장'](#reliable-node-후보-저장) 과정을 통해서 Reliable Node 후보들을 가지고 있다. 선정 방법은 후
네.. 그런데 노드 규모가 10-30명정도니까, 그리고 rpc로 이미 다 연결이 되어있다고 하니까  동기화를 할때마다 height싱크를 맞춰줘도 될 것 같습니다. (block이 추가될때마다 싱크를 맞추는 것이 아니라)

2018-06-24 07:34 UTC, zeroFruit commented on blockchain/PROJECT-IMPLEMENTATION-DETAILS-KR.md
> +먼저 확인(Check)은 (1) '신뢰할 수 있는 노드'(Reliable Node) 선정과 (2) '상태 점검'을 거친다. Reliable Node를 선정하기 위해서 blockchain 컴포넌트는 ['Reliable Node 후보 저장'](#reliable-node-후보-저장) 과정을 통해서 Reliable Node 후보들을 가지고 있다. 선정 방법은 후
동기화를 하려고 할때만 peer-table height 싱크를 맞춰주는 것은 어떤가요. 노드의 규모가 10-30이고 rpc로 연결되어있다고하니까 데이터를 가져오는데 그리 큰 시간이 걸리진 않을 것 같네요.

음.. 동기화할때만 height 싱크를 맞춰도 충분할 것 같은 것이, 블록 싱크때 말고 height가 필요한 때가 leader선정 등일 것 같은데, 이때 필요한게 제 생각엔 정확한 height값이 아니라 '누가 height가 가장 크냐'일 거 같습니다. 만약 동기화가 일어나지 않고 평화롭게 각자 합의된 블럭들을 추가하고 있는 상황이라면 peer-table의 height가 outdated된것일지라도 크기 관계는 변하지 않을 것 같습니다.

2018-06-24 07:35 UTC, zeroFruit commented on blockchain/PROJECT-IMPLEMENTATION-DETAILS-KR.md
> +먼저 확인(Check)은 (1) '신뢰할 수 있는 노드'(Reliable Node) 선정과 (2) '상태 점검'을 거친다. Reliable Node를 선정하기 위해서 blockchain 컴포넌트는 ['Reliable Node 후보 저장'](#reliable-node-후보-저장) 과정을 통해서 Reliable Node 후보들을 가지고 있다. 선정 방법은 후
+그리고 싱크는 height가 가장 긴 노드한테서 가져오는 것으로...

2018-06-24 08:20 UTC, zeroFruit commented on blockchain/PROJECT-IMPLEMENTATION-DETAILS-KR.md
> +먼저 확인(Check)은 (1) '신뢰할 수 있는 노드'(Reliable Node) 선정과 (2) '상태 점검'을 거친다. Reliable Node를 선정하기 위해서 blockchain 컴포넌트는 ['Reliable Node 후보 저장'](#reliable-node-후보-저장) 과정을 통해서 Reliable Node 후보들을 가지고 있다. 선정 방법은 후
@junbeomlee @frontalnh @byron1st @hea9549 @hihiboss @junk-sound 
의견 부탁드립니다!

2018-06-24 14:12 UTC, frontalnh approved these changes

2018-06-24 14:34 UTC, junbeomlee commented
블록체인 동기화 그림의 화질이 조금 낮은 것 같습니다!

2018-06-24 15:27 UTC, zeroFruit commented
그림이 다시보니 조금 작은거 그냥 같아서 두개로 분리했습니다.

2018-06-25 05:10 UTC, junbeomlee approved these changes

2018-06-25 05:10 UTC, junbeomlee commented
@junk-sound @zeroFruit 머지해도 될 것 같습니다~!

2018-06-25 05:11 UTC, junbeomlee commented
브런치 삭제 해주세요~!

2018-06-25 05:55 UTC, junbeomlee commented
제가 머지하고 삭제하겠습니다~!

2018-06-25 05:55 UTC, merged