rename  files in the .tmp folder and Clear files in the .tmp folder before start
DE-labtory/it-chain pull request #964
Opened 2018-10-11 03:27 UTC by JoosJuliet

resolved: #941 

details: 
When deploying a icode, if you deploy other icode, an error occurs and you need to modify it so that it can be deployed in parallel

1. Rename files in the tmp folder
(example learn-icode_Eunn3RaaTnzWlVZQarcvDrvHnzu77npMtcuyMFPj)
2. Clear files in the .tmp folder before start

 - [ ] Test case

2018-10-11 04:43 UTC, junngo requested changes
몇몇 의견을 남겨 보겠습니다 :)

2018-10-11 04:43 UTC, junngo commented on cmd/on/ivmfx/ivmfx.go
> +}
engine/cmd/on/init.go에서 clearFolder()라는 시작 전 폴더 삭제 부분이 존재합니다. clearFolder()에 포함하는 것이 괜찮을 것 같다는 생각이 됩니다 :)

2018-10-11 04:43 UTC, junngo commented on ivm/infra/git/icode_git_store.go
> +	metaData := ivm.NewICode(id, name, repositoryUrl, baseSavePath+"/"+name+"_"+i, commitHash, version)
아래의 커밋들과 하나로 합쳐있을 때 하나의 커밋 단위로 유지보수나 분석이 쉬울 것 같다는 생각이 됩니다.

2018-10-11 05:46 UTC, junbeomlee commented
goimports 적용해주세요!!

2018-10-15 12:22 UTC, junbeomlee commented
commit정리해주세요!! 그리고 conflict부분이 있어서 rebase로 맞춰야 할 것 같습니다!

2018-10-20 10:24 UTC, junbeomlee approved these changes

2018-10-20 10:25 UTC, merged